import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { ArrowLeft, Check, ChevronLeft, ChevronRight, Loader2, Plus, Ruler, RotateCcw, X } from 'lucide-react'
import { useState, type FormEvent } from 'react'
import { Link } from 'react-router-dom'
import { useDialogFocus } from '@/components/laundry/useDialogFocus'
import { apiGet, apiPatch, apiPost } from '@/lib/api'

type ServiceUnit = { id: string; value: string; fullName: string; shortName: string; active: boolean; builtIn: boolean; usageCount: number }
type UnitInput = { fullName: string; shortName: string }
const blankUnit: UnitInput = { fullName: '', shortName: '' }

export default function LaundryServiceUnits() {
  const client = useQueryClient()
  const [adding, setAdding] = useState(false)
  const [viewing, setViewing] = useState<ServiceUnit | null>(null)
  const [editing, setEditing] = useState<ServiceUnit | null>(null)
  const [archiving, setArchiving] = useState<ServiceUnit | null>(null)
  const [pageSize, setPageSize] = useState(100)
  const [page, setPage] = useState(1)
  const [notice, setNotice] = useState('')
  const units = useQuery({ queryKey: ['laundry-service-units'], queryFn: () => apiGet<ServiceUnit[]>('/laundry/settings/service-units') })
  const save = useMutation({
    mutationFn: ({ id, draft }: { id?: string; draft: UnitInput }) => id
      ? apiPatch<ServiceUnit>(`/laundry/settings/service-units/${encodeURIComponent(id)}`, draft)
      : apiPost<ServiceUnit>('/laundry/settings/service-units', draft),
    onSuccess: () => {
      client.invalidateQueries({ queryKey: ['laundry-service-units'] })
      client.invalidateQueries({ queryKey: ['laundry-catalogue'] })
      setAdding(false); setEditing(null); setViewing(null)
      setNotice('Service unit saved. New catalogue selections will use the updated unit.')
    },
  })
  const setActive = useMutation({
    mutationFn: ({ unit, active }: { unit: ServiceUnit; active: boolean }) => apiPatch<ServiceUnit>(`/laundry/settings/service-units/${encodeURIComponent(unit.id)}`, { active }),
    onSuccess: (_result, variables) => {
      client.invalidateQueries({ queryKey: ['laundry-service-units'] })
      client.invalidateQueries({ queryKey: ['laundry-catalogue'] })
      setArchiving(null)
      setNotice(variables.active ? 'Service unit restored.' : 'Service unit archived. It is kept in this settings list and can be restored.')
    },
  })
  const rows = units.data || []
  const pageCount = Math.max(1, Math.ceil(rows.length / pageSize))
  const currentPage = Math.min(page, pageCount)
  const start = rows.length ? (currentPage - 1) * pageSize + 1 : 0
  const end = Math.min(currentPage * pageSize, rows.length)
  const visibleRows = rows.slice(start ? start - 1 : 0, end)

  return <div className="mx-auto max-w-5xl animate-in fade-in slide-in-from-bottom-2 duration-300">
    <Link to="/laundry/settings" className="inline-flex min-h-9 items-center gap-2 rounded-lg px-2 text-sm font-bold text-[#5740cb] hover:bg-[#f3f0ff] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#664cf0]"><ArrowLeft className="h-4 w-4" />Back to Settings</Link>
    <div className="mt-4 flex flex-wrap items-end justify-between gap-4">
      <div><p className="text-[10px] font-extrabold uppercase tracking-[.16em] text-[#664cf0]">Catalog</p><h1 className="mt-1 font-serif text-3xl text-[#241a45]">Service Units</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-[#6f6982]">Name the way staff measure garments or services. The short name is used where space is tight.</p></div>
      <button type="button" onClick={() => { save.reset(); setNotice(''); setAdding(true) }} className="inline-flex min-h-10 items-center gap-2 rounded-xl bg-[#664cf0] px-4 py-2.5 text-sm font-bold text-white shadow-sm transition hover:bg-[#5740cb] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#664cf0] focus-visible:ring-offset-2"><Plus className="h-4 w-4" />Add Unit</button>
    </div>
    {notice ? <p role="status" className="mt-4 rounded-xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm font-semibold text-emerald-800">{notice}</p> : null}

    <section aria-label="Service units" className="mt-6 overflow-hidden rounded-2xl border border-[#272043]/10 bg-white shadow-[0_8px_28px_rgba(32,23,60,.04)]">
      <div className="flex items-center gap-3 border-b border-[#272043]/8 px-5 py-4"><span className="grid h-9 w-9 place-items-center rounded-xl bg-[#eeeaff] text-[#5740cb]"><Ruler className="h-4 w-4" /></span><div className="min-w-0 flex-1"><h2 className="text-sm font-extrabold text-[#241a45]">Unit list</h2><p className="text-xs text-[#77718a]">{units.isLoading ? 'Loading…' : `${rows.length} units`}</p></div><button type="button" aria-label="Refresh service units" onClick={() => void units.refetch()} className="grid h-9 w-9 place-items-center rounded-lg text-[#5740cb] hover:bg-[#f5f2ff]"><RotateCcw className="h-4 w-4" /></button></div>
      {units.isLoading ? <p className="flex items-center justify-center gap-2 p-10 text-sm text-[#77718a]"><Loader2 className="h-4 w-4 animate-spin" />Loading service units…</p>
        : units.error ? <div className="p-6"><p role="alert" className="rounded-xl bg-rose-50 p-3 text-sm text-rose-700">{units.error instanceof Error ? units.error.message : 'Could not load service units.'}</p><button type="button" onClick={() => void units.refetch()} className="mt-3 rounded-lg border border-[#ded9f7] px-3 py-2 text-sm font-bold text-[#5740cb]">Try again</button></div>
          : rows.length ? <div className="divide-y divide-[#272043]/8">{visibleRows.map((unit) => <div key={unit.id} className="flex flex-wrap items-center gap-3 px-5 py-4"><span className="grid h-10 w-10 shrink-0 place-items-center rounded-xl bg-[#f5f2ff] text-[#664cf0]"><Ruler className="h-4 w-4" /></span><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><h3 className="truncate text-sm font-bold text-[#332849]">{unit.fullName}</h3><span className="rounded-full bg-[#f3f0ff] px-2.5 py-1 text-[10px] font-bold text-[#5843bd]">{unit.shortName}</span>{unit.builtIn ? <span className="rounded-full bg-[#edf5ff] px-2.5 py-1 text-[10px] font-bold text-[#316c9c]">Standard</span> : null}{!unit.active ? <span className="rounded-full bg-[#f1eff5] px-2.5 py-1 text-[10px] font-bold text-[#686479]">Archived</span> : null}</div><p className="mt-1 text-xs text-[#77718a]">{unit.usageCount ? `Used by ${unit.usageCount} active catalogue item${unit.usageCount === 1 ? '' : 's'}` : 'Not used by an active garment or service'}{unit.builtIn ? ' · Included in Epic Laundry' : ''}</p></div><div className="flex items-center gap-2"><button type="button" onClick={() => setViewing(unit)} className="min-h-9 rounded-lg border border-[#ded9f7] px-3 py-1.5 text-xs font-bold text-[#5740cb] hover:bg-[#f8f7ff]">View unit</button>{unit.active ? <button type="button" onClick={() => setArchiving(unit)} disabled={unit.builtIn || unit.usageCount > 0} title={unit.builtIn ? 'Standard units stay available' : unit.usageCount > 0 ? 'Remove this unit from active garments and services first' : undefined} className="min-h-9 rounded-lg border border-[#e4d6d6] px-3 py-1.5 text-xs font-bold text-[#93504c] hover:bg-[#fff6f5] disabled:cursor-not-allowed disabled:opacity-50">Archive</button> : <button type="button" onClick={() => setActive.mutate({ unit, active: true })} disabled={setActive.isPending} className="min-h-9 rounded-lg border border-[#ded9f7] px-3 py-1.5 text-xs font-bold text-[#5740cb] hover:bg-[#f8f7ff]">Restore</button>}</div><button type="button" aria-label={`Edit ${unit.fullName}`} onClick={() => setViewing(unit)} className="grid h-9 w-9 place-items-center rounded-lg text-[#5740cb] hover:bg-[#f5f2ff]"><ChevronRight className="h-4 w-4" /></button></div>)}</div>
          : <div className="px-6 py-14 text-center"><span className="mx-auto grid h-12 w-12 place-items-center rounded-2xl bg-[#f2efff] text-[#664cf0]"><Ruler className="h-5 w-5" /></span><h2 className="mt-3 text-base font-extrabold text-[#332849]">No Data Found</h2><p className="mx-auto mt-1 max-w-sm text-sm leading-5 text-[#77718a]">Add a unit name and short name so staff can choose how to measure work.</p><button type="button" onClick={() => setAdding(true)} className="mt-4 inline-flex min-h-9 items-center gap-2 rounded-lg border border-[#664cf0]/20 bg-white px-3 py-2 text-xs font-bold text-[#5740cb] hover:bg-[#f8f7ff]"><Plus className="h-3.5 w-3.5" />Add Unit</button></div>}
      {rows.length ? <div className="flex flex-wrap items-center justify-between gap-3 border-t border-[#272043]/8 px-5 py-3 text-xs text-[#6b667b]" aria-live="polite"><span>Showing {start}–{end} of {rows.length}</span><div className="flex items-center gap-2"><label htmlFor="service-unit-page-size" className="font-semibold">Items per page</label><select id="service-unit-page-size" aria-label="Items per page" value={pageSize} onChange={(event) => { setPageSize(Number(event.target.value)); setPage(1) }} className="rounded-lg border border-[#342a63]/15 bg-white px-2 py-1.5 font-semibold text-[#423b52]">{[10, 20, 50, 100, 500].map((size) => <option key={size} value={size}>{size}</option>)}</select><button type="button" aria-label="Previous page" disabled={currentPage <= 1} onClick={() => setPage((value) => Math.max(1, value - 1))} className="rounded-lg border border-[#342a63]/15 p-1.5 disabled:cursor-not-allowed disabled:opacity-40"><ChevronLeft className="h-4 w-4" /></button><span className="min-w-12 text-center">{currentPage} / {pageCount}</span><button type="button" aria-label="Next page" disabled={currentPage >= pageCount} onClick={() => setPage((value) => Math.min(pageCount, value + 1))} className="rounded-lg border border-[#342a63]/15 p-1.5 disabled:cursor-not-allowed disabled:opacity-40"><ChevronRight className="h-4 w-4" /></button></div></div> : null}
    </section>
    {viewing ? <UnitDetails unit={viewing} onEdit={() => { setEditing(viewing); setViewing(null); save.reset() }} onClose={() => setViewing(null)} /> : null}
    {adding || editing ? <UnitForm key={editing?.id || 'new'} unit={editing} saving={save.isPending} error={save.error} onClose={() => { setAdding(false); setEditing(null); save.reset() }} onSave={(draft) => save.mutate({ id: editing?.id, draft })} /> : null}
    {archiving ? <ArchiveUnitDialog unit={archiving} saving={setActive.isPending} error={setActive.error} onClose={() => setArchiving(null)} onConfirm={() => setActive.mutate({ unit: archiving, active: false })} /> : null}
  </div>
}

function UnitDetails({ unit, onEdit, onClose }: { unit: ServiceUnit; onEdit: () => void; onClose: () => void }) {
  const dialog = useDialogFocus<HTMLDivElement, HTMLButtonElement>(onClose)
  return <div className="fixed inset-0 z-50 grid place-items-center bg-[#17122b]/55 p-4 backdrop-blur-sm" onMouseDown={(event) => { if (event.target === event.currentTarget) onClose() }}><div ref={dialog.dialogRef} role="dialog" aria-modal="true" aria-labelledby="service-unit-view-title" tabIndex={-1} onKeyDown={dialog.onKeyDown} className="w-full max-w-md rounded-2xl bg-white p-5 shadow-2xl sm:p-6"><div className="flex items-start justify-between gap-3"><div><p className="text-[10px] font-extrabold uppercase tracking-[.15em] text-[#664cf0]">Service Units</p><h2 id="service-unit-view-title" className="mt-1 font-serif text-2xl text-[#241a45]">View Unit</h2></div><button ref={dialog.initialFocusRef} type="button" aria-label="Close unit details" onClick={onClose} className="grid h-9 w-9 place-items-center rounded-lg text-[#686479] hover:bg-[#f5f2ff]"><X className="h-4 w-4" /></button></div><dl className="mt-5 space-y-3"><div className="rounded-xl bg-[#faf9fd] p-3"><dt className="text-xs font-bold text-[#77718a]">Full Unit Name</dt><dd className="mt-1 text-sm font-semibold text-[#332849]">{unit.fullName}</dd></div><div className="rounded-xl bg-[#faf9fd] p-3"><dt className="text-xs font-bold text-[#77718a]">Short Unit Name</dt><dd className="mt-1 text-sm font-semibold text-[#332849]">{unit.shortName}</dd></div></dl><div className="mt-5 flex justify-end gap-2"><button type="button" onClick={onClose} className="min-h-10 rounded-xl border border-[#d8d2ee] px-4 py-2 text-sm font-bold text-[#514b67]">Close</button><button type="button" onClick={onEdit} className="min-h-10 rounded-xl bg-[#664cf0] px-4 py-2 text-sm font-bold text-white">Edit Service Unit</button></div></div></div>
}

function UnitForm({ unit, saving, error, onClose, onSave }: { unit: ServiceUnit | null; saving: boolean; error: unknown; onClose: () => void; onSave: (draft: UnitInput) => void }) {
  const [form, setForm] = useState<UnitInput>(() => unit ? { fullName: unit.fullName, shortName: unit.shortName } : blankUnit)
  const dialog = useDialogFocus<HTMLDivElement, HTMLButtonElement>(onClose)
  function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); onSave({ fullName: form.fullName.trim(), shortName: form.shortName.trim() }) }
  const valid = Boolean(form.fullName.trim() && form.shortName.trim())
  return <div className="fixed inset-0 z-50 grid place-items-center bg-[#17122b]/55 p-4 backdrop-blur-sm" onMouseDown={(event) => { if (event.target === event.currentTarget) onClose() }}><div ref={dialog.dialogRef} role="dialog" aria-modal="true" aria-labelledby="service-unit-form-title" tabIndex={-1} onKeyDown={dialog.onKeyDown} className="w-full max-w-lg rounded-2xl bg-white p-5 shadow-2xl sm:p-6"><div className="flex items-start justify-between gap-3"><div><p className="text-[10px] font-extrabold uppercase tracking-[.15em] text-[#664cf0]">Service Units</p><h2 id="service-unit-form-title" className="mt-1 font-serif text-2xl text-[#241a45]">{unit ? 'Edit Service Unit' : 'Add Service Unit'}</h2></div><button ref={dialog.initialFocusRef} type="button" aria-label="Close service unit form" onClick={onClose} className="grid h-9 w-9 place-items-center rounded-lg text-[#686479] hover:bg-[#f5f2ff]"><X className="h-4 w-4" /></button></div><form className="mt-5 space-y-4" onSubmit={submit}><label className="block text-sm font-semibold text-[#423b52]">Full Unit Name *<input autoFocus={!unit} required maxLength={100} value={form.fullName} onChange={(event) => setForm({ ...form, fullName: event.target.value })} placeholder="Enter full unit name" className="mt-1.5 w-full rounded-xl border border-[#342a63]/15 px-3 py-2.5 font-normal outline-none focus:ring-2 focus:ring-[#664cf0]/30" /><span className="mt-1 block text-right text-[11px] font-normal text-[#77718a]">{form.fullName.length}/100</span></label><label className="block text-sm font-semibold text-[#423b52]">Short Unit Name *<input required maxLength={10} value={form.shortName} onChange={(event) => setForm({ ...form, shortName: event.target.value })} placeholder="Enter short unit name" className="mt-1.5 w-full rounded-xl border border-[#342a63]/15 px-3 py-2.5 font-normal outline-none focus:ring-2 focus:ring-[#664cf0]/30" /><span className="mt-1 block text-right text-[11px] font-normal text-[#77718a]">{form.shortName.length}/10</span></label>{error ? <p role="alert" className="rounded-xl bg-rose-50 px-3 py-2 text-sm text-rose-700">{error instanceof Error ? error.message : 'Could not save this service unit.'}</p> : null}<div className="flex justify-end gap-2 border-t border-[#272043]/8 pt-4"><button type="button" onClick={onClose} className="min-h-10 rounded-xl border border-[#d8d2ee] px-4 py-2 text-sm font-bold text-[#514b67]">Cancel</button><button type="submit" disabled={saving || !valid} className="inline-flex min-h-10 items-center gap-2 rounded-xl bg-[#664cf0] px-4 py-2 text-sm font-bold text-white disabled:cursor-not-allowed disabled:opacity-50"><Check className="h-4 w-4" />{saving ? 'Saving…' : 'Save'}</button></div></form></div></div>
}

function ArchiveUnitDialog({ unit, saving, error, onClose, onConfirm }: { unit: ServiceUnit; saving: boolean; error: unknown; onClose: () => void; onConfirm: () => void }) {
  const dialog = useDialogFocus<HTMLDivElement, HTMLButtonElement>(onClose)
  return <div className="fixed inset-0 z-50 grid place-items-center bg-[#17122b]/55 p-4 backdrop-blur-sm" onMouseDown={(event) => { if (event.target === event.currentTarget) onClose() }}><div ref={dialog.dialogRef} role="dialog" aria-modal="true" aria-labelledby="archive-service-unit-title" tabIndex={-1} onKeyDown={dialog.onKeyDown} className="w-full max-w-md rounded-2xl bg-white p-5 shadow-2xl"><p className="text-[10px] font-extrabold uppercase tracking-[.15em] text-[#664cf0]">Service Units</p><h2 id="archive-service-unit-title" className="mt-1 font-serif text-xl text-[#241a45]">Archive {unit.fullName}?</h2><p className="mt-2 text-sm leading-5 text-[#6f6982]">Staff can no longer choose this unit for new catalogue items. You can restore it later. Existing order records keep their original unit name.</p>{error ? <p role="alert" className="mt-3 rounded-xl bg-rose-50 px-3 py-2 text-sm text-rose-700">{error instanceof Error ? error.message : 'Could not archive this service unit.'}</p> : null}<div className="mt-5 flex justify-end gap-2"><button ref={dialog.initialFocusRef} type="button" onClick={onClose} className="min-h-10 rounded-xl border border-[#d8d2ee] px-4 py-2 text-sm font-bold text-[#514b67]">Cancel</button><button type="button" disabled={saving} onClick={onConfirm} className="min-h-10 rounded-xl bg-[#93504c] px-4 py-2 text-sm font-bold text-white disabled:opacity-50">{saving ? 'Archiving…' : 'Archive Unit'}</button></div></div></div>
}
