import { expect, test } from '@playwright/test'

test('weighted laundry shows its unit and books with a discount larger than the charge', async ({ page }) => {
  await page.goto('/ui/app/?local-demo=1#/laundry/dashboard')
  await page.getByRole('button', { name: 'Sign in' }).click()
  await expect(page.locator('aside').first()).toBeVisible()
  const catalogue = await (await page.request.get('/api/laundry/catalogue')).json()
  const charge = catalogue.chargeRules.find((rule: { name: string }) => rule.name === 'Premium Express Delivery')
  const discount = catalogue.discountRules.find((rule: { name: string }) => rule.name === 'Welcome Offer')
  expect(charge).toBeTruthy()
  expect(discount).toBeTruthy()
  await page.goto('/ui/app/?local-demo=1#/laundry/new-order')
  await page.getByRole('textbox', { name: 'Search customers by name or phone' }).fill('Demo Priya')
  await page.getByRole('button', { name: /Demo Priya 9000000101/ }).click()
  const mixed = page.locator('article').filter({ hasText: 'Mixed clothes' }).first()
  await mixed.getByRole('button', { name: 'Add', exact: true }).click()
  await expect(mixed.getByRole('spinbutton', { name: 'Quantity of Mixed clothes' })).toHaveValue('1')
  await mixed.getByRole('spinbutton', { name: 'Quantity of Mixed clothes' }).fill('0.1')
  await page.getByRole('button', { name: 'Edit Mixed clothes', exact: true }).click()
  await page.getByRole('spinbutton', { name: 'Price override for Mixed clothes' }).fill('50')
  await expect(page.getByText('0.1 kg × ₹50/kg = ₹5', { exact: true })).toBeVisible()
  await page.locator('article').filter({ hasText: 'Polo shirt' }).first().getByRole('button', { name: 'Add', exact: true }).click()
  await page.getByRole('button', { name: 'Edit Polo shirt', exact: true }).click()
  await page.getByRole('spinbutton', { name: 'Price override for Polo shirt' }).fill('640')
  await page.getByRole('combobox', { name: 'Charge', exact: true }).selectOption(charge.id)
  const quoteReady = page.waitForResponse((response) => {
    if (!response.url().endsWith('/api/laundry/quote') || response.request().method() !== 'POST') return false
    return response.request().postDataJSON()?.discountRuleIds?.includes(discount.id)
  })
  await page.getByRole('combobox', { name: 'Discount', exact: true }).selectOption(discount.id)
  const quote = await (await quoteReady).json()
  expect(quote.discounts).toBeGreaterThan(quote.charges)
  expect(quote.grandTotal).toBe(748.71)
  await expect(page.getByText('Grand total', { exact: true }).locator('..')).toContainText('₹748.71')
  await expect(page.getByText('0.1 kg · 1 piece', { exact: true })).toBeVisible()
  const bookingReady = page.waitForResponse((response) => new URL(response.url()).pathname === '/api/laundry/orders' && response.request().method() === 'POST')
  await page.getByRole('button', { name: 'Book order', exact: true }).click()
  const bookingResponse = await bookingReady
  expect(bookingResponse.status(), await bookingResponse.text()).toBe(201)
  const booked = await bookingResponse.json()
  expect(booked.order.grandTotal).toBe(quote.grandTotal)
  expect(booked.receipt.items[0]).toMatchObject({ qty: 0.1, rate: 50, amount: 5, unit: 'Kilogram' })
  await expect(page.getByText('Order booked', { exact: true })).toBeVisible()
  await expect(page.getByText(/invoice line \d+ rate cannot be negative/)).toHaveCount(0)
})
