// Importing each module registers its routes with the router in core.ts.
import './dashboard'
import './catalogue'
import './orders'
import './tracking'
import './online'
import './finance'
import './statistics'
import './packages'
import './settings'
import './reports'
import './operations'
import './marketplaceCatalogue'
import './counterDesk'
import './quote'
